name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.60.6.91
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~/slr-predictor
            git pull origin main
            sudo systemctl restart fastapi
